version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/Chatbot
    environment:
      - FLASK_ENV=development
    command: python -m unittest testChatbot.py
